import { Nav } from "@/components/layout/Nav";
import { Footer } from "@/components/layout/Footer";

export const metadata = {
  title: "Privacy Policy | Designs by Jeninne",
  description: "How Designs by Jeninne collects, uses, and protects your information.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="w-full bg-ink">
        <section className="relative min-h-[30vh] flex items-center justify-center px-6 md:px-12 pt-32 pb-16">
          <div className="max-w-3xl mx-auto text-center">
            <div className="text-xs font-sans font-medium tracking-[0.3em] text-gold-500 uppercase mb-6">
              Legal
            </div>
            <h1 className="font-serif text-5xl md:text-6xl font-light leading-tight text-ivory mb-6">
              Privacy Policy
            </h1>
            <p className="font-sans text-sm text-warmgray">
              Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
            </p>
          </div>
        </section>

        <section className="pb-24 md:pb-32 px-6 md:px-12">
          <div className="max-w-3xl mx-auto space-y-10 font-sans text-warmgray leading-relaxed">
            <p>
              Designs by Jeninne (&quot;we,&quot; &quot;us,&quot; &quot;our&quot;) respects your privacy.
              This page explains what information we collect when you use this website, why we collect
              it, and how it&apos;s handled.
            </p>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Information We Collect</h2>
              <p className="mb-3">When you submit a project inquiry or booking, we collect:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Your name, email address, and phone number</li>
                <li>Project details, preferred date and time, and location information you provide</li>
                <li>Payment proof (receipt images or PDFs) you upload to confirm a booking</li>
              </ul>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">How We Use It</h2>
              <p>
                We use this information solely to respond to your inquiry, plan and deliver your booked
                project, calculate applicable travel fees, and communicate with you about your booking or
                payment. We do not sell or rent your information to third parties.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Third-Party Services</h2>
              <p className="mb-3">We rely on a small number of trusted services to run this site:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong className="text-ivory">Resend</strong> — delivers the confirmation and
                  notification emails generated by your submissions.
                </li>
                <li>
                  <strong className="text-ivory">Google Maps</strong> — powers address autocomplete on
                  the booking form so you can search for and select a location.
                </li>
                <li>
                  <strong className="text-ivory">Vercel</strong> — hosts this website and may collect
                  basic, anonymized analytics (such as page views) to help us understand site usage.
                </li>
              </ul>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Payment Information</h2>
              <p>
                We do not process card payments directly on this site. Payment is made via bank transfer,
                and the receipt you upload as proof of payment is sent securely to us by email for manual
                verification. We do not store payment receipts in a public or searchable database.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Data Retention &amp; Security</h2>
              <p>
                We retain booking and inquiry information only as long as needed to complete your project
                and for reasonable record-keeping afterward. We take reasonable steps to protect your
                information, but no method of electronic transmission or storage is completely secure.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Your Rights</h2>
              <p>
                You may contact us at any time to ask what information we hold about you, request a
                correction, or request that we delete it, subject to any records we&apos;re required to
                keep for legitimate business purposes.
              </p>
            </div>

            <div>
              <h2 className="font-serif text-2xl text-ivory mb-4">Contact Us</h2>
              <p>
                Questions about this policy or your information can be sent to{" "}
                <a
                  href="mailto:info@designsbyjeninne.com"
                  className="text-gold-500 hover:text-gold-300 transition-colors"
                >
                  info@designsbyjeninne.com
                </a>
                .
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
